- lib/perfSONAR_PS/NPToolkit/Config/RegularTesting.pm
- lib/perfSONAR_PS/NPToolkit/DataService/RegularTesting.pm
> Toolkit109

- lib/perfSONAR_PS/Utils/Host.pm
Andy, here is my patch to detect Xen guests.  Let me know if you think there's something missing or should be done differently.
Thanks,
> Adding Xen virtualised host detection.

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
- lib/perfSONAR_PS/Utils/Host.pm
This goes with toolkit branches interface-counters and interface-selector
> Shared interface counters

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
This is the perl-shared part of the changes required to add more host status info.
> Added more host status info and made a Details popover for some of it

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
- lib/perfSONAR_PS/Utils/GeoLookup.pm
> change geoip lookups Shared 24

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
- lib/perfSONAR_PS/Utils/Host.pm
This goes with the intf_aliases_toolkit branch
> Intf aliases shared

- lib/perfSONAR_PS/Client/PScheduler/Task.pm
- lib/perfSONAR_PS/Client/PScheduler/TaskManager.pm
Records task/tool(src->dest) for the task that produced the error.
Fixes perfsonar/mesh-config#65
> Log short task info in case of pscheduler errors

- lib/perfSONAR_PS/Client/PScheduler/Task.pm
- lib/perfSONAR_PS/Client/Utils.pm
- lib/perfSONAR_PS/NPToolkit/Config/LSRegistrationDaemon.pm
- lib/perfSONAR_PS/NPToolkit/ConfigManager/ConfigClient.pm
- lib/perfSONAR_PS/NPToolkit/DataService/RegularTesting.pm
- lib/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm
Related to https://github.com/perfsonar/toolkit/issues/265 and going along with https://github.com/perfsonar/mesh-config/pull/100
Looks good to merge to me.
> Fix UTF-8 chars in test descriptions

- lib/perfSONAR_PS/NPToolkit/DataService/RegularTesting.pm
- lib/perfSONAR_PS/RegularTesting/Utils/ConfigFile.pm
Trying to solve https://github.com/perfsonar/toolkit/issues/265
> Tests and Hosts description in utf8

- lib/perfSONAR_PS/Utils/Host.pm
Debian Stretch VM reported as not virtual.
> Fix Virtual Machine detection for Xen

- Makefile
- lib/perfSONAR_PS/Client/PSConfig/Translators/MeshConfig/Config.pm
- lib/perfSONAR_PS/Client/PSConfig/Translators/MeshConfigTasks/Config.pm
- libperfsonar.spec
Merge 4.1.3 into master for tagging
> 4.1.3 merge into master

- Makefile
- lib/perfSONAR_PS/Client/PSConfig/Parsers/TaskGenerator.pm
- libperfsonar.spec
- t/client-psconfig-taskgenerator.t
> Merge 4.1.3 into 4.2.0

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
Reporting everything as errors is confusing for users.
> Update log levels for reporting host status in LS

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
> jsonsummary#248

- lib/perfSONAR_PS/Client/PScheduler/TaskManager.pm
Tracks tasks in queue to be created in addition to ones already on server.
> Fix for psconfig duplicate task issue

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
- lib/perfSONAR_PS/Utils/Host.pm
Separating commits for each issue. Corresponding toolkit commit 'd1bb391e57dd91187350653e9e6385cef8286401'
> Changes for Toolkit#128

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
Separating commit for toolkit#283, corresponding toolkit commit '06e016f33613cabed9250cfd77991701d8c648fd'
> Changes for toolkit#283

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
Separating commit for toolkit#274, corresponding toolkit commit '30b19445ec74cf22661b3e8c2aa213872288570d'
> Changes for toolkit#274

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
- lib/perfSONAR_PS/Utils/LookupService.pm
Separating commit for toolkit#281
> Changes for toolkit#281

- lib/perfSONAR_PS/NPToolkit/Config/AdministrativeInfo.pm
- lib/perfSONAR_PS/NPToolkit/Config/LSRegistrationDaemon.pm
- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
Reverts perfsonar/perl-shared#80 which waw the previous implementation for toolkit#373 that we don't need anymore.
> Revert "Configurable privacy policy text and link added toolkit#373"

- lib/perfSONAR_PS/NPToolkit/DataService/Host.pm
This somehow did not get merged properly in #63 ... Merging now
> TCP_INFO values - Tcp#128
